# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('acronym', models.TextField(max_length=10)),
                ('location', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform', models.IntegerField()),
                ('from_custom_base26', models.IntegerField()),
                ('get_pig_latin', models.IntegerField()),
                ('top_chars', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dbfolder', models.TextField()),
                ('dropout', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.College')),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.Student'),
        ),
    ]
