# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='email',
            new_name='contact',
        ),
    ]
