# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0002_auto_20160601_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='contact',
            new_name='email',
        ),
    ]
